### ISSUE TITLE
Mentions does not work

### ISSUE THREAD

**Issue by walkerbox** [spyder007/teamcity-msteams-notifier#10]
Hello,
Thank you a lot for your work.
I'm trying to configure user mentions for my TeamCity builds - they do not work. Can you privede an instruction, how does the plugin maps users? How to configure this function? I can see, the code responsible for mentioning is commented out in MsTeamsNotificationImpl.java, cound you please tell why?

**Comment by spyder007** [comment]
User mentions, as best I can see, aren't currently supported in the Incoming Webhooks.  It looks like it's still an ["Under Review" feature request](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/17153099-webhook-needs-to-support-forced-notification-a-la) in Teams.
