### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by Rustamer** [spyder007/teamcity-msteams-notifier#11]
There are problems with the encoding. When transmitting Cyrillic names get question marks in MS Teams in the fields Triggered by the description of the changes. There are no such problems in TeamCIty itself. 
P.S. Mercurial is used as a version control system.

**Comment by Rustamer** [comment]
![screenshot 2019-06-07 001](https://user-images.githubusercontent.com/51479892/59100706-4fb9ce00-8940-11e9-8e94-e29aeda3e4cb.png)

**Comment by spyder007** [comment]
The implementation pulls data from the [SBuild](http://javadoc.jetbrains.net/teamcity/openapi/9.1/jetbrains/buildServer/serverSide/SBuild.html) class and stores those values in a temporary class.  That class is then serialized using the com.google.gson.

There is no explicit encoding/decoding done in the plugin, so it's possible that the is an encoding/decoding issue in either the JetBrains Teamcity libraries OR the GSON libraries.  It's also possible that the MS Teams webhook doesn't like the characters being sent.

If you set your log level to INFO, there should be a server log with the following prefix:
**MsTeamsNotificationListener :: Body message will be**

followed by the entirety of the JSON message that is sent to the Teams Incoming Webhook.  Would you be able to check your Teamcity Server logs for that message and determine if the Cyrillic characters are correct in that message?  if they are not, it's probably one of the libraries above.  if they ARE, then it's an issue with the HTTP post to MS Teams.

On the side, i'm working on updating the Jetbrains and GSON libraries to their latest versions (updating to Teamcity 2019.1).  If we determine it's a library issue, I can release version 2.0 with the latest Teamcity versions for you.

**Comment by anivaros** [comment]
Checked my server, in log all OK:
```json
[2019-07-02 17:58:06,679]   INFO -   jetbrains.buildServer.SERVER - MsTeamsNotificationListener :: Body message will be 
{
    "@context": "http://schema.org/extensions",
    "@type": "MessageCard",
    "sections": [
        {
            "activityImage": "https://raw.githubusercontent.com/spyder007/teamcity-msteams-notifier/master/docs/TeamCity72x72.png",
            "activityTitle": "ExecutiveWorkspace",
            "facts": [
                {
                    "name": "Branch",
                    "value": "releases/release-4.8.0"
                },
                {
                    "name": "Triggered by",
                    "value": "Anisimov Vasiliy"
                },
                {
                    "name": "Agent",
                    "value": "ordo-ios-build-agent"
                },
                {
                    "name": "Elapsed",
                    "value": "5m:33s"
                }
            ],
            "startGroup": false
        },
        {
            "facts": [
                {
                    "name": "bfefeb23ee",
                    "value": "anisimov.v :: Включил локальные уведомления о новых документах для СОГАЗа\n"
                },
                {
                    "name": "633e3b3625",
                    "value": "anisimov.v :: Фикс падения при отсутствии атрибутов\nДобавил проверку на наличие аттача перед генерацией превьюшки\n"
                },
                {
                    "name": "a028f1a967",
                    "value": "anisimov.v :: Фикс лага при вводе пин кода\n"
                },
                {
                    "name": "3122b0d6b1",
                    "value": "anisimov.v :: Версия приложения - 4.8.0\n"
                },
                {
                    "name": "43a90aee0d",
                    "value": "anisimov.v :: Перенёс libxslt в под\n"
                },
                {
                    "name": "More",
                    "value": "(+ 256)\n"
                }
            ],
            "startGroup": false,
            "text": "Changes By ars, sorokin.m, zelinskaya.a, anisimov.v",
            "title": "Commits"
        }
    ],
    "text": "[Succeeded - Проекты ОРДО / Executive Workspace iOS / 4.8.0 / Build and Deploy / ExecutiveWorkspace #4.8.0.2](http://ddsm-teamcity.digdes.com/viewLog.html?buildTypeId=ORDO_ExecutiveWorkspaceIOS_480_BuildAndDeploy_ExecutiveWorkspace&buildId=47601)",
    "themeColor": "008900"
}
```

**Comment by spyder007** [comment]
That's what I was afraid of.. if they are ok in the log files, then it could be that Microsoft's incoming web hooks don't like those characters coming in.

Would you be able to try a postman post to Microsoft with some test characters?

**Comment by anivaros** [comment]
I just checked same request via `curl` in terminal and all fine:

`curl -X POST "https://outlook.office.com/webhook/..." -H "accept: text/plain" -H "Content-Type: application/json" -d "{\"@type\":\"MessageCard\",\"@context\":\"http://schema.org/extensions\",\"text\":\"[Succeeded - Проекты ОРДО / Executive Workspace iOS / 4.8.0 / Build and Deploy / ExecutiveWorkspace #4.8.0.2](http://ddsm-teamcity.digdes.com/viewLog.html?buildTypeId\u003dORDO_ExecutiveWorkspaceIOS_480_BuildAndDeploy_ExecutiveWorkspace\u0026buildId\u003d47601)\",\"themeColor\":\"008900\",\"sections\":[{\"activityImage\":\"https://raw.githubusercontent.com/spyder007/teamcity-msteams-notifier/master/docs/TeamCity72x72.png\",\"activityTitle\":\"ExecutiveWorkspace\",\"startGroup\":false,\"facts\":[{\"name\":\"Branch\",\"value\":\"releases/release-4.8.0\"},{\"name\":\"Triggered by\",\"value\":\"Anisimov Vasiliy\"},{\"name\":\"Agent\",\"value\":\"ordo-ios-build-agent\"},{\"name\":\"Elapsed\",\"value\":\"5m:33s\"}]},{\"title\":\"Commits\",\"text\":\"Changes By ars, sorokin.m, zelinskaya.a, anisimov.v\",\"startGroup\":false,\"facts\":[{\"name\":\"bfefeb23ee\",\"value\":\"anisimov.v :: Включил локальные уведомления о новых документах для СОГАЗа\n\"},{\"name\":\"633e3b3625\",\"value\":\"anisimov.v :: Фикс падения при отсутствии атрибутов\nДобавил проверку на наличие аттача перед генерацией превьюшки\n\"},{\"name\":\"a028f1a967\",\"value\":\"anisimov.v :: Фикс лага при вводе пин кода\n\"},{\"name\":\"3122b0d6b1\",\"value\":\"anisimov.v :: Версия приложения - 4.8.0\n\"},{\"name\":\"43a90aee0d\",\"value\":\"anisimov.v :: Перенёс libxslt в под\n\"},{\"name\":\"More\",\"value\":\"(+ 256)\n\"}]}]}"`

![Screenshot 2019-07-02 at 20 06 38](https://user-images.githubusercontent.com/873387/60532068-19842a00-9d05-11e9-8c07-95b2ce7c4296.png)

**Comment by spyder007** [comment]
Ok, perhaps it's something with the mechanism in the plugin that is making the post.. I'll assign this to myself to test.

**Comment by elkhovd** [comment]
@anivaros Did you find the solution?

**Comment by anivaros** [comment]
> @anivaros Did you find the solution?

Yes, I've quit the company and don't use Teams anymore
