### ISSUE TITLE
Empty Builds (all & sub-projects) tab

### ISSUE THREAD

**Issue by anivaros** [spyder007/teamcity-msteams-notifier#16]
Hi! Awesome plugin, thanks a lot for your work!

I've found strange behaviour - I can't select which subproject to notify because of there are no sub-projects 😕

![Screenshot 2019-07-02 at 17 45 36](https://user-images.githubusercontent.com/873387/60522438-a58c5680-9cf1-11e9-844e-929bce18b74c.png)

**Comment by spyder007** [comment]
This looks to be something with the way the height is set on that pane.  This code is pulled from the slack notifications plugin, which is a little older.  It's currently trying to reference jquery 1.4.3, which could be the problem.  I'll assign this to myself and figure out the best way to set the height of that box appropriately.

**Comment by spyder007** [comment]
This is fixed with [Release 2.0.3](https://github.com/spyder007/teamcity-msteams-notifier/releases/tag/2.0.3)
