### ISSUE TITLE
Icons doesn't appear

### ISSUE THREAD

**Issue by nrudnyk** [spyder007/teamcity-msteams-notifier#18]
So I've provided icons for both your plugin and teams incoming webhook, 
<img width="409" alt="image" src="https://user-images.githubusercontent.com/20221382/67090652-53ddde00-f1b3-11e9-9629-7b305f9b8b31.png">
but no luck
<img width="177" alt="Screenshot 2019-10-18 at 14 22 59" src="https://user-images.githubusercontent.com/20221382/67090546-111c0600-f1b3-11e9-954a-0f93f4e5a552.png">

Am I missing something? Or it's a teams bug?

**Comment by chaami** [comment]
Hi,
I think that the icon that is broken is the one associated to the channel webhook.
So I would double check the setting of the webhook instead of the MsTeams settings.
Are you sure that the url that you provided is reachable from the internet ?
Kind regards.

**Comment by nrudnyk** [comment]
I believe webhook settings requires uploading image
<img width="544" alt="image" src="https://user-images.githubusercontent.com/20221382/67220935-564e6b00-f433-11e9-8cbe-97f86d42dc94.png">

for MsTeams notifier settings I used the following, and yes, it should be reachable here:https://www.scichart.com/wp-content/uploads/2019/10/teamcity-icon-logo-png-transparent.png

**Comment by chaami** [comment]
On afterthought, I was wondering if your image is not actually too big for some obscure Teams limitations...
Have you tried / Can you try with the plugin default image (https://raw.githubusercontent.com/spyder007/teamcity-msteams-notifier/master/docs/TeamCity72x72.png) to see if it's better ?

**Comment by nrudnyk** [comment]
you were right, it's some obscure Teams limitation, but the other image doesn't work still. Do you have any ideas why?
<img width="166" alt="image" src="https://user-images.githubusercontent.com/20221382/69007350-6a5b8e80-0945-11ea-83f5-4b166e70036e.png">
