### ISSUE TITLE
Message customization

### ISSUE THREAD

**Issue by see-dev** [spyder007/teamcity-msteams-notifier#19]
Hi guys! 

Will it be possible to add custom message to a build notification? The thing is that we have different parameters of a build (TeamCity params), and it would be great to see some critical of them all in the notification. Or maybe it is possible right now?

Thanks,
Eugene

**Comment by thiagoguardadobeltran** [comment]
I would really like to see the parameters on the notification as well

**Comment by spyder007** [comment]
Generally, notifications are meant to bring the user into TeamCity to review, not necessarily to provide all the information required.  The built in Teams notifications don't allow for any real customization of the message.  This notifier, which is based on the old slack notifier, has SOME small options (checkboxes) to send things like build agent/elapsed time/committers/commits/failure reason, but, outside of that, I think it's probably bad practice to allow things like teamcity parameters to be thrown out in notifications.  If it were configurable enough to be useful in that regard, then there would be the need to filter parameters based on whether or not they are hidden.

Although I can certainly see the use case, I have preferred to keep this a simple notifier based on Teamcity's own notification system, rather then build a full-fledged automated messaging.  The latter would require message templating at various levels among other improvements.
