### ISSUE TITLE
Give Link to Build Artifacts in Teams Message

### ISSUE THREAD

**Issue by zhandzlik** [spyder007/teamcity-msteams-notifier#23]
Is it possible to list the build artifacts in the build step and provide the links to the build steps? TeamCity allows linking to build artifacts in the email notifier and I was curious if this feature is possible with the MS teams plugin? Thanks!

**Comment by spyder007** [comment]
As of their latest [documentation](https://www.jetbrains.com/help/teamcity/2019.2/customizing-notifications.html), Teamcity does not have a built-in way to list build artifacts within email notifications.  It looks like there may be some plugins to allow for this, but nothing internal.

A general feature enhancement for this would be to allow for the customization of the messages, however, I'm not sure that I have the time to attack that at this point.  I'll leave this open for a time in case anyone else wants to tackle it.

**Comment by spyder007** [comment]
Actually, my message customization is a duplicate of Issue #19
