### ISSUE TITLE
Trying to create a group notification rule fails in sql insert step

### ISSUE THREAD

**Issue by skolima** [spyder007/teamcity-msteams-notifier#3]
Samples SQL being run:

```
insert into usergroup_watch_type (rule_id, group_id, notificator_type, watch_type, watch_value, order_num) 
values (11, ALL_USERS_GROUP, tcMsTeamsBuildNotifier, 2, _Root, 1)
```

result:

```
Msg 8152, Level 16, State 14, Line 4
String or binary data would be truncated.
The statement has been terminated.
```

The column `notificator_type` is `varchar 20` and the value for the Slack notifier ('tcSlackBuildNotifier') fits in there, while the one for this notifier is too long.

**Comment by spyder007** [comment]
I guess no one has been creating group notifications on our side.  Merged your change in.
