### ISSUE TITLE
Not working with Teamcity 2019.2.3

### ISSUE THREAD

**Issue by elementum** [spyder007/teamcity-msteams-notifier#35]
It just not working with Teamcity 2019.2.3
It's configured correctly, test notification works just fine, but no notifications come if a build fails.

**Comment by elementum** [comment]
Ok, I figured it out.
I failed to fulfill this part _From the MsTeams tab on the Project or Build Configuration page_ because there is no a link to MsTeams seen on those pages. So I went directly to _http://link.to.your.server/msteamsnotifications/index.html?projectId=your_project_ and configured notifications.

**Comment by lynnroth** [comment]
I believe I'm seeing the same issue on 2020.1 (build 78475).  No link to MSTeams on Project or build pages, but the link provided by @elementum does work.

**Comment by opejanovic** [comment]
I am experiencing the same issue with TC 2020.2.4 (build 86063)

**Comment by opejanovic** [comment]
![image](https://user-images.githubusercontent.com/16704836/118125617-85527600-b3f7-11eb-965b-f9d7ab8c81a6.png)
Test notification works but the link points to http://buildserver/build and I cannot find where it could be configured.

**Comment by spyder007** [comment]
![image](https://user-images.githubusercontent.com/4701399/118137400-2975f600-b3d3-11eb-8951-344007286286.png)
That page can be accessed from the "More" dropdown in the new TC User interface.

Regarding the root project, I'm not sure you were ever to save notification preferences at the root project level, it doesn't seem you can do that with other notifications (email, slack)
