### ISSUE TITLE
Add branch filter

### ISSUE THREAD

**Issue by jrobertson-insite** [spyder007/teamcity-msteams-notifier#36]
I can't seem to find a way to filter notifications by branch. This was in the Slack notifier I used and assumed it would be here too. Am I missing this or would I need to add it and make a PR?

**Comment by spyder007** [comment]
The plugin uses Teamcity's own notification events to trigger notifications.  I haven't checked the slack plugin to see if that's configurable.

Generally, though, I think it's outside of the scope of this plugin:  it's really meant to provide another channel through which to send notifications from TeamCity.
