### ISSUE TITLE
Problem with Czech characters in notification

### ISSUE THREAD

**Issue by han-rastax** [spyder007/teamcity-msteams-notifier#43]
Hi, we are using your plugin in our company and we are from Czech republic. Sometimes we have project names in Czech language and our names are with Czech characters "+ěščřžýáíéůú" and received messages in MS Teams shows in the wrong encoding. See to attachment, can you look into for this issue.

![Teams - Notification](https://user-images.githubusercontent.com/77144239/103990210-25219e00-5191-11eb-8c54-f88cd76c5bb3.png)

The correct project name is GŘC and correct Triggered by is Antonín Koláček

**Comment by elkhovd** [comment]
Same with cyrillic
![image](https://user-images.githubusercontent.com/26866823/119969200-f036ac00-bfb6-11eb-89ba-e165a3e737d9.png)
