### ISSUE TITLE
Opportunity to configure settings depending on a branch 

### ISSUE THREAD

**Issue by TimurIskahov** [spyder007/teamcity-msteams-notifier#45]
I have a project where several branches are being built. 
![image](https://user-images.githubusercontent.com/35902086/105316839-7b9bcd00-5bd2-11eb-8670-f70ab7076879.png)
I want to add notifications only for a specific branch.
Is it possible?

**Comment by spyder007** [comment]
This plugin is built off of the Notifications module in TeamCity:  it does not determine when notifications are sent, only where they are sent.
https://www.jetbrains.com/help/teamcity/notifications.html

The same branch filters that are available in the built in notifiers are also available with this plugin.
