### ISSUE TITLE
Teams shows the following warning: "Your connector is running on old configuration. Navigate to connector configuration window to update to new configuration."

### ISSUE THREAD

**Issue by zgabi** [spyder007/teamcity-msteams-notifier#46]
Please update it to the new configuration.

**Comment by cbayles** [comment]
This is a change with Teams webhook url format. In Teams on the channel you send TeamCity messages to, you have to right click and go to channel settings, Connectors, Manage the TeamCity connector, you should see a button to Update Url. Save and Copy the new url and paste it into the webhook url in TeamCity in the notifier settings.

This will be the case for any other older webhooks you have setup in Teams. Here's a help article that describes the issue https://answers.microsoft.com/en-us/msteams/forum/all/microsoft-teams-important-your-connector-is/59452bf4-f87a-4503-9bfb-a8333724bee5

**Comment by zgabi** [comment]
@cbayles Thank you for your answer.

I can't find the channel settings on the right click on the channel. Do you mean "Manage Channel"?
![image](https://user-images.githubusercontent.com/3104253/110814294-9a8d1600-8289-11eb-99a2-c4552a940311.png)

When I click to "Manage Channel", there is no Connectors.

However there is a "Connectors" on the context menu of the channel. (first screenshot), but I can't find the TeamCity connentor in the dialog shown:
![image](https://user-images.githubusercontent.com/3104253/110814629-e770ec80-8289-11eb-96fd-a8d1fd0c63ae.png)

Could you please help me where can I find that url?

**Comment by cbayles** [comment]
In your second screenshot on the Connectors page, left menu under Manage > Configured, it'll show a down arrow that will show Configured connectors. Click Manage next to your TeamCity one.

**Comment by zgabi** [comment]
@cbayles Thank you very much. Solved.
