### ISSUE TITLE
Is it possible to customize "sender's" name?

### ISSUE THREAD

**Issue by opejanovic** [spyder007/teamcity-msteams-notifier#53]
![image](https://user-images.githubusercontent.com/16704836/123417838-924ab380-d5b8-11eb-9577-ac5192005be1.png)

**Comment by spyder007** [comment]
It looks like something has changed with the incoming webhooks in Teams. I had to manage my configured webhooks and add a name to the connector.

Although the configuration allows you to define a Bot Name, that value cannot be used when sending the payload:  the name comes from the connector's name.
