### ISSUE TITLE
a way to disable notifications for a few subprojects?

### ISSUE THREAD

**Issue by mdagit** [spyder007/teamcity-msteams-notifier#59]
We have a deeply nested teamcity project hierarchy, and out of maybe 100 jobs there are around 5 that
are run regularly but that we really don't care about (or at least, don't want them going to the same channel).
It is very convenient to be able to set up the msteams notification at a root folder, but I don't see an
easy way to exclude just a few sub-projects (either at the top-level config, or at the individual sub-job config).

**Comment by spyder007** [comment]
This plugin relies on the notifications system within teamcity for configuring when notifications are sent.  This plugin only controls how the notification is sent.  I'd check the TeamCity docs to see if there's a way to configure notifications for sub-projects.

**Comment by mdagit** [comment]
@spyder007 I'm not sure what you mean by such reliance. For example, isn't the config dialog shown in this screenshot entirely under the control of the plugin?

<img width="465" alt="Screen Shot 2022-01-03 at 11 21 05 AM" src="https://user-images.githubusercontent.com/6396794/147971104-22c9b5d5-7efb-4cfc-8243-ad1a7c6b5d9d.png">

So in theory it could support excluding some projects instead of "all or none"? 
Or some kind of +/- pattern set component like teamcity often uses?
