### ISSUE TITLE
Do not see project-specific settings?

### ISSUE THREAD

**Issue by blindzero** [spyder007/teamcity-msteams-notifier#62]
Hi,
we've installed latest version (2.0.9) and successfully configured on root level, test submission worked.
Unfortunately we cannot see any project- or build-config specific configuration page?
As we have one large build server instance it's necessary for us to have different WebHooks configured per project.
Can you please advice?
Thanks,
M.

**Comment by spyder007** [comment]
If you navigate to the project, you should see an **MsTeams** tab on the far right, and, from there, you can add Project Level Settings.

Similarly, if you navigate to the Build Configuration, you should see the same **MsTeams** tab on the right.  

Note that these are NOT available in the Edit Configuration screens, only in the normal view screens.
