### ISSUE TITLE
java.io.IOException: Attempted read from closed stream.  MS changed the Teams response

### ISSUE THREAD

**Issue by Eric-Maddox** [spyder007/teamcity-msteams-notifier#72]
I found the issue in logsteamcity-server.log on the build server. 
java.io.IOException: Attempted read from closed stream.
at msteamsnotifications.MsTeamsNotificationImpl.postViaWebHook(MsTeamsNotificationImpl.java:184)

Microsoft made a change that broke things for many people. 
The change in the Webhook is documented here: https://github.com/MicrosoftDocs/msteams-docs/issues/7830

**Comment by Eric-Maddox** [comment]
The closed stream error happens because we get a 400 from the server and then try to read the results back twice, once as an error message and again as content.  The stream can only be read once.

**Comment by Eric-Maddox** [comment]
MsTeamsNotification failed :  returned error Bad payload received by generic incoming webhook. 

The 400 error is because the notification is sending JSON, but sending the content type header application/x-www-form-urlencoded

**Comment by spyder007** [comment]
Should be fixed by #73 , thanks @Eric-Maddox !
